export const LINK_DRIBBBLE = "https://dribbble.com/MateuszHadrys"
export const LINK_GITHUB = "https://github.com/hadrysmateusz"
export const LINK_MEDIUM = "https://medium.com/@hadrysmateusz"
export const LINK_TWITTER = "https://twitter.com/HadrysMateusz"
export const EMAIL = "contact@hadrysmateusz.com"
